[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/day"
  to = "/.netlify/functions/day"
  status = 200

[[redirects]]
  from = "/api/groupme"
  to = "/.netlify/functions/groupme"
  status = 200
